service: eshippers
frameworkVersion: "3"

resources:
  Resources:
    MetaDataDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: shipperImageTable
        AttributeDefinitions:
          - AttributeName: image_url
            AttributeType: S
        KeySchema:
          - AttributeName: image_url
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UploadRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: upload-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:PutObjectAcl
                  Resource: !Sub
                    - "arn:aws:s3:::${BucketName}/*"
                    - { BucketName: "shipper-files" }
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource:
                    - "Fn::GetAtt": [MetaDataDynamoDbTable, Arn]
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    Fn::Sub:
                      - arn:aws:logs:${Region}:${AccountId}:log-group:/aws/lambda/*:*:*
                      - {
                          Region: !Ref AWS::Region,
                          AccountId: !Ref AWS::AccountId,
                        }

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"

functions:
  uploader:
    handler: upload.handle
    events:
      - http: POST /file/upload
    role: UploadRole
    environment:
      BUCKET: shipper-files
      TABLE_NAME: !Ref MetaDataDynamoDbTable
